### ISSUE TITLE
Not using OpenAPI v2 json spec

### ISSUE THREAD

**Issue by platy** [danielgtaylor/restish#12]
My api is using a json openapi v2 spec hosted at /openapi.json. When I configure it there is no error and I see in the server logs that both /openapi.yaml and /openapi.json are requested. But when I try `restish example --help` or anything else I get the below error and in the server log I see that only the yaml is requested.

```
% restish example --help
panic: could not detect API type: http://localhost:8080/

goroutine 1 [running]:
github.com/danielgtaylor/restish/cli.Run()
	/home/runner/work/restish/restish/cli/cli.go:447 +0x777
main.main()
	/home/runner/work/restish/restish/main.go:27 +0x177
```

I installed using homebrew.

**Comment by danielgtaylor** [comment]
@platy only OpenAPI 3 is supported. Restish will see your OpenAPI 2 file but will refuse to process it because it's not supported. I do not plan to add OpenAPI 2 support as 3 has been out for a long time (since mid-2017). If you can't update the API, then Restish can read an OpenAPI 3 spec from a local file as an alternative.

**Comment by platy** [comment]
Thanks very much, that explains it. I'll try using a translator and using it locally

**Comment by danielgtaylor** [comment]
Example config in `~/.restish/apis.json` that uses a file on disk:

```json
{
  "stripe": {
    "base": "https://api.stripe.com",
    "spec_files": ["/Users/example/src/stripe-openapi.yaml"],
    "profiles": {
      "default": {}
    }
  }
}
```
