### ISSUE TITLE
number parsing: raw results != non raw results

### ISSUE THREAD

**Issue by mping-exo** [danielgtaylor/restish#130]
Steps to reproduce:

1. Create eg: mock api with reply  `{"id": 573311229116900865}`
2. Use `restish`, observe number getting "truncated"
3. Use `restish -r`, observe raw response

I know javascript engines will have an issue with eg: this number:
```
❯ node                   
Welcome to Node.js v13.1.0.
Type ".help" for more information.
> 573311229116900865
573311229116900860
>
```

Please advise if this is expected behaviour.

**Comment by wdullaer** [comment]
I did some investigation into this.
The problem seems to be that internally the json is deserialized into a `map[interface{}]interface{}`. Since `json.Unmarshal` has no type information it choses to use `float64` to deserialize number values. This is on par with other json implementations.

If you deserialize into a concrete type (say `int64`), `json.Unmarshal` will do the right thing and no precision is lost.

Theoretically, if the openapi spec provides detailed type information, we could try to be smarter when deserializing, but I didn't immediately see a quick fix.

**Comment by danielgtaylor** [comment]
Thanks for looking into this. It's a pretty difficult problem for a generic tool to solve. At this point I'm going to say this is expected behavior as so many implementations behave this way.

Also from the [JSON RFC](https://www.rfc-editor.org/rfc/rfc8259#section-6):

> Note that when such software is used, numbers that are integers and
   are in the range `[-(2**53)+1, (2**53)-1]` are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.

If you need to send around big numbers a common tactic in JSON is to encode them to strings. Other formats like [CBOR have built-in support for big numbers](https://www.rfc-editor.org/rfc/rfc7049#section-2.4.2).
