### ISSUE TITLE
running cloned code

### ISSUE THREAD

**Issue by kpayson** [danielgtaylor/restish#40]
What are the commands to build and install the code cloned from Github?  (I've just been debuging through vs code but this has its limits)

How can I switch back and forth between the code I built and what is brew installed?  When I'm developing a restish feature, I want want the restish command to refer to my local development instance.

What is the current release schedule?  When do you plan to publish again?

Also, ss it possible to 'stable' releases, and 'nightly' releases?

**Comment by danielgtaylor** [comment]
For running locally you can just do `go run .` and it'll run your local code. You can also `go install` and it will put the binary into `$GOPATH/bin/restish` instead of the Homebrew location of `/usr/local/bin/restish`. You can use the full path to run either one any time, and set your `PATH` environment variable to prefer one over the other if needed.

I don't have a release schedule, but try to release whenever significant changes come in. I plan to do another release within the next few days if that helps.

I don't think nightlies make sense as the project isn't active enough. I probably just need to get better about more frequent releases. Something like https://github.com/semantic-release/semantic-release could help.
