### ISSUE TITLE
Post csv file not working

### ISSUE THREAD

**Issue by idali0226** [danielgtaylor/restish#49]
I have Restful service with post to upload csv file. 
When run: restish post http://localhost:8180/upload <georg_batch.csv, I got error:

HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Length: 240
Content-Type: text/html;charset=UTF-8
Date: Fri, 28 May 2021 06:19:23 GMT

com.fasterxml.jackson.core.JsonParseException: Unrecognized token &#x27;Id&#x27;: was expecting &#x27;null&#x27;, &#x27;true&#x27;, &#x27;false&#x27; or NaN
 at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 4]
(base)

**Comment by danielgtaylor** [comment]
@idali0226 this is because you have not provided a content type for the `POST` request, and so Restish defaults to `application/json` and it looks like your server is interpreting that to mean "decode this as JSON" which fails because it is CSV. You can set a content type to work around this:

```sh
$ restish post :8180/upload -H "Content-Type: text/csv" <georg_batch.csv
```

I'll think about whether it makes sense to keep that default.

**Comment by danielgtaylor** [comment]
I think I will leave the default behavior as-is since JSON is the lingua franca of HTTP APIs. I'm going to close this, but feel free to reopen if you like!
