### ISSUE TITLE
got error while file is correct in swagger and redocly

### ISSUE THREAD

**Issue by iShift** [danielgtaylor/restish#76]
goroutine 1 [running]:
github.com/danielgtaylor/restish/cli.Run()
	/home/runner/work/restish/restish/cli/cli.go:496 +0x94c
main.main()
	/home/runner/work/restish/restish/main.go:27 +0x238

How I can verify openapi file with restish and get more information?

**Comment by danielgtaylor** [comment]
It is causing a panic due to an error loading the OpenAPI file here: https://github.com/danielgtaylor/restish/blob/main/cli/cli.go#L495-L497

Any additional info? Can you share the OpenAPI?

**Comment by iShift** [comment]
sorry, u couldn't share, maybe i can use command/library for verification open API file?
Because in redoc/swagger the file works as expected.

**Comment by danielgtaylor** [comment]
The parse we use is https://github.com/getkin/kin-openapi, which you can try to use to dig in to what might be going on.

I'm going to close this issue since we can't repro or anything, but feel free to re-open if you figure out what is going on or have a small example you can share. Alternatively we can use email to privately share your OpenAPI, just let me know what you want to do.
